name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Build the Docker image for the frontend
        # Build the Docker image and tag it as 'cluyverth-web'
      - name: Build Docker Image for Frontend
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ github.repository }}/cluyverth-web:latest .

      # Step 3: Login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Push the Docker image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/cluyverth-web:latest

      # Step 5: Deploy the new container on your VPS via SSH using Podman
          # Stop and remove the existing container if it exists
          # Pull the latest image from GHCR
          # Run the new container, mapping container port 80 to host port 3000
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            podman stop cluyverth-web || true
            podman rm cluyverth-web || true
            podman pull ghcr.io/${{ github.repository }}/cluyverth-web:latest
            podman run -d --name cluyverth-web -p 3000:80 ghcr.io/${{ github.repository }}/cluyverth-web:latest
