name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set REPO variable
      - name: Set REPO variable
        run: echo "REPO=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 3: Build the Docker image for the frontend
      - name: Build Docker Image for Frontend
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ env.REPO }}/cluyverth-web:latest .

      # Step 4: Login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Push Docker Image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPO }}/cluyverth-web:latest

      # Step 6: Deploy to VPS via SSH using Podman Compose
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            # Navigate to the directory where podman-compose.yml is located
            cd ~/Projects
            # Pull the latest images and restart containers
            podman-compose pull
            podman-compose up -d
