name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Build da imagem Docker para o frontend
      - name: Build Docker Image for Frontend
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      # Passo 3: Login no GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Passo 4: Push da imagem para o GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

      # Passo 5: Deploy no VPS via SSH
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/Projects/Cluyverth-Portfolio
            podman-compose pull
            podman-compose up -d
